[General]
appLaunchCountsJson="{\"waypaper\":5,\"com.discordapp.Discord\":3,\"sh.ppy.osu\":5,\"org.prismlauncher.PrismLauncher\":10,\"steam\":3,\"com.spotify.Client\":2,\"qalculate-gtk\":3,\"dev.zed.Zed\":4,\"mullvad-vpn\":3}"
themeName=adwaita-dark
