[General]
appLaunchCountsJson="{\"waypaper\":8,\"com.discordapp.Discord\":4,\"sh.ppy.osu\":7,\"org.prismlauncher.PrismLauncher\":15,\"steam\":6,\"com.spotify.Client\":4,\"qalculate-gtk\":5,\"dev.zed.Zed\":4,\"mullvad-vpn\":3,\"emacs\":1,\"Dune Awakening\":1}"
themeName=compline-dark
