[General]
appLaunchCountsJson="{\"/var/lib/flatpak/exports/share/applications/com.discordapp.Discord.desktop\":3,\"com.discordapp.Discord\":3,\"firewall-config\":1,\"dev.zed.Zed\":2}"
themeName=light
